import { Restaurant, MenuItem, Order, User, Address, PaymentMethod } from './types';

import { mariasRestaurant } from './competitorPricing';

export const mockRestaurants: Restaurant[] = [
  mariasRestaurant,
  {
    id: '1',
    name: "Mama Rosa's Trattoria",
    cuisine: 'Italian',
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: '25-40 min',
    deliveryFee: 3.99,
    distance: 1.2,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: true,
    description: 'Family-owned Italian restaurant serving authentic pasta and wood-fired pizzas since 1985.',
    priceRange: '$$',
    hours: '11:00 AM - 10:00 PM',
    address: '123 Main St, Downtown',
  },
  {
    id: '2',
    name: 'Sakura Sushi Bar',
    cuisine: 'Japanese',
    rating: 4.6,
    reviewCount: 218,
    deliveryTime: '30-45 min',
    deliveryFee: 4.49,
    distance: 2.1,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: true,
    description: 'Fresh sushi and sashimi made with locally-sourced fish.',
    priceRange: '$$$',
    hours: '12:00 PM - 11:00 PM',
    address: '456 Ocean Ave, Waterfront',
  },
  {
    id: '3',
    name: 'Burger Joint',
    cuisine: 'American',
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: '20-35 min',
    deliveryFee: 3.99,
    distance: 0.8,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop',
    isLocallyOwned: false,
    isPartner: true,
    description: 'Gourmet burgers with premium beef and fresh toppings.',
    priceRange: '$$',
    hours: '10:00 AM - 12:00 AM',
    address: '789 Burger Ln, Midtown',
  },
  {
    id: '4',
    name: 'Thai Spice Garden',
    cuisine: 'Thai',
    rating: 4.7,
    reviewCount: 189,
    deliveryTime: '35-50 min',
    deliveryFee: 4.99,
    distance: 3.2,
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: true,
    description: 'Authentic Thai cuisine with a modern twist. Family recipes passed down for generations.',
    priceRange: '$$',
    hours: '11:30 AM - 10:00 PM',
    address: '321 Spice Rd, Eastside',
  },
  {
    id: '5',
    name: 'Taco Fiesta',
    cuisine: 'Mexican',
    rating: 4.5,
    reviewCount: 423,
    deliveryTime: '20-30 min',
    deliveryFee: 3.99,
    distance: 1.5,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: true,
    description: 'Street-style tacos and fresh guacamole made daily.',
    priceRange: '$',
    hours: '10:00 AM - 11:00 PM',
    address: '654 Fiesta St, Westside',
  },
  {
    id: '6',
    name: 'Green Leaf Cafe',
    cuisine: 'Vegetarian',
    rating: 4.9,
    reviewCount: 156,
    deliveryTime: '25-40 min',
    deliveryFee: 3.99,
    distance: 1.8,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: true,
    description: 'Plant-based dishes that nourish body and soul. 100% organic ingredients.',
    priceRange: '$$',
    hours: '8:00 AM - 9:00 PM',
    address: '987 Green Way, Uptown',
  },
  {
    id: '7',
    name: 'Dragon Palace',
    cuisine: 'Chinese',
    rating: 4.3,
    reviewCount: 298,
    deliveryTime: '30-45 min',
    deliveryFee: 4.49,
    distance: 2.5,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop',
    isLocallyOwned: true,
    isPartner: false,
    description: 'Traditional Cantonese and Szechuan dishes.',
    priceRange: '$$',
    hours: '11:00 AM - 11:00 PM',
    address: '147 Dragon Ave, Chinatown',
  },
  {
    id: '8',
    name: 'Pizza Paradise',
    cuisine: 'Italian',
    rating: 4.2,
    reviewCount: 512,
    deliveryTime: '25-40 min',
    deliveryFee: 3.99,
    distance: 1.0,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&auto=format&fit=crop',
    isLocallyOwned: false,
    isPartner: true,
    description: 'New York style pizza with fresh mozzarella daily.',
    priceRange: '$',
    hours: '11:00 AM - 2:00 AM',
    address: '258 Slice St, Downtown',
  },
];

export const mockMenuItems: MenuItem[] = [
  // Mama Rosa's Trattoria
  {
    id: 'm1',
    restaurantId: '1',
    name: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with egg, Pecorino Romano, guanciale, and black pepper',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&auto=format&fit=crop',
    category: 'Pasta',
    popular: true,
    addOns: [
      { id: 'a1', name: 'Extra Parmesan', price: 2.00 },
      { id: 'a2', name: 'Grilled Chicken', price: 5.00 },
      { id: 'a3', name: 'Garlic Bread', price: 3.50 },
    ],
    dietary: [],
  },
  {
    id: 'm2',
    restaurantId: '1',
    name: 'Margherita Pizza',
    description: 'San Marzano tomatoes, fresh mozzarella, basil, and extra virgin olive oil',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&auto=format&fit=crop',
    category: 'Pizza',
    popular: true,
    addOns: [
      { id: 'a4', name: 'Extra Cheese', price: 2.50 },
      { id: 'a5', name: 'Pepperoni', price: 3.00 },
      { id: 'a6', name: 'Mushrooms', price: 2.00 },
    ],
    dietary: ['vegetarian'],
  },
  {
    id: 'm3',
    restaurantId: '1',
    name: 'Chicken Parmigiana',
    description: 'Breaded chicken breast topped with marinara and melted mozzarella, served with spaghetti',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400&auto=format&fit=crop',
    category: 'Entrees',
    popular: false,
    addOns: [
      { id: 'a7', name: 'Side Salad', price: 4.50 },
      { id: 'a8', name: 'Extra Sauce', price: 1.00 },
    ],
  },
  {
    id: 'm4',
    restaurantId: '1',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&auto=format&fit=crop',
    category: 'Dessert',
    popular: true,
    addOns: [],
    dietary: ['vegetarian'],
  },
  // Sakura Sushi Bar
  {
    id: 'm5',
    restaurantId: '2',
    name: 'Dragon Roll',
    description: 'Eel and cucumber inside, topped with avocado and eel sauce',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=400&auto=format&fit=crop',
    category: 'Sushi Rolls',
    popular: true,
    addOns: [
      { id: 'a9', name: 'Extra Eel Sauce', price: 1.00 },
      { id: 'a10', name: 'Spicy Mayo', price: 0.50 },
    ],
  },
  {
    id: 'm6',
    restaurantId: '2',
    name: 'Salmon Sashimi',
    description: 'Fresh salmon slices, 8 pieces',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&auto=format&fit=crop',
    category: 'Sashimi',
    popular: true,
    addOns: [
      { id: 'a11', name: 'Extra Wasabi', price: 0.50 },
      { id: 'a12', name: 'Extra Ginger', price: 0.50 },
    ],
  },
  {
    id: 'm7',
    restaurantId: '2',
    name: 'Miso Soup',
    description: 'Traditional soybean paste soup with tofu and wakame',
    price: 3.99,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&auto=format&fit=crop',
    category: 'Soups',
    popular: false,
    addOns: [],
    dietary: ['vegetarian', 'vegan'],
  },
  // Burger Joint
  {
    id: 'm8',
    restaurantId: '3',
    name: 'The Classic Burger',
    description: 'Premium beef patty, lettuce, tomato, onion, pickles, and house sauce',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop',
    category: 'Burgers',
    popular: true,
    addOns: [
      { id: 'a13', name: 'Bacon', price: 2.50 },
      { id: 'a14', name: 'Avocado', price: 2.00 },
      { id: 'a15', name: 'Extra Patty', price: 4.00 },
      { id: 'a16', name: 'Fries', price: 3.99 },
    ],
  },
  {
    id: 'm9',
    restaurantId: '3',
    name: 'Truffle Fries',
    description: 'Crispy fries tossed with truffle oil and parmesan',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&auto=format&fit=crop',
    category: 'Sides',
    popular: true,
    addOns: [
      { id: 'a17', name: 'Extra Truffle Oil', price: 1.50 },
      { id: 'a18', name: 'Truffle Aioli', price: 1.00 },
    ],
    dietary: ['vegetarian'],
  },
  // Thai Spice Garden
  {
    id: 'm10',
    restaurantId: '4',
    name: 'Pad Thai',
    description: 'Rice noodles stir-fried with egg, tofu, bean sprouts, and crushed peanuts',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&auto=format&fit=crop',
    category: 'Noodles',
    popular: true,
    addOns: [
      { id: 'a19', name: 'Chicken', price: 4.00 },
      { id: 'a20', name: 'Shrimp', price: 5.00 },
      { id: 'a21', name: 'Extra Peanuts', price: 1.00 },
    ],
  },
  {
    id: 'm11',
    restaurantId: '4',
    name: 'Green Curry',
    description: 'Coconut milk curry with bamboo shoots, Thai basil, and bell peppers',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&auto=format&fit=crop',
    category: 'Curry',
    popular: true,
    addOns: [
      { id: 'a22', name: 'Jasmine Rice', price: 2.50 },
      { id: 'a23', name: 'Extra Vegetables', price: 2.00 },
    ],
  },
  // Taco Fiesta
  {
    id: 'm12',
    restaurantId: '5',
    name: 'Street Tacos (3)',
    description: 'Corn tortillas with your choice of protein, onions, cilantro, and salsa',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&auto=format&fit=crop',
    category: 'Tacos',
    popular: true,
    addOns: [
      { id: 'a24', name: 'Extra Salsa', price: 0.75 },
      { id: 'a25', name: 'Guacamole', price: 2.50 },
      { id: 'a26', name: 'Queso', price: 2.00 },
    ],
  },
  {
    id: 'm13',
    restaurantId: '5',
    name: 'Burrito Bowl',
    description: 'Rice, beans, protein, pico de gallo, cheese, sour cream, and guacamole',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400&auto=format&fit=crop',
    category: 'Bowls',
    popular: true,
    addOns: [
      { id: 'a27', name: 'Double Protein', price: 4.00 },
      { id: 'a28', name: 'Extra Guac', price: 2.00 },
    ],
  },
  // Green Leaf Cafe
  {
    id: 'm14',
    restaurantId: '6',
    name: 'Buddha Bowl',
    description: 'Quinoa, roasted vegetables, chickpeas, avocado, and tahini dressing',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&auto=format&fit=crop',
    category: 'Bowls',
    popular: true,
    addOns: [
      { id: 'a29', name: 'Extra Avocado', price: 2.50 },
      { id: 'a30', name: 'Hemp Seeds', price: 1.50 },
    ],
    dietary: ['vegan', 'gluten-free'],
  },
  {
    id: 'm15',
    restaurantId: '6',
    name: 'Acai Bowl',
    description: 'Acai blend topped with granola, fresh berries, and coconut flakes',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400&auto=format&fit=crop',
    category: 'Breakfast',
    popular: true,
    addOns: [
      { id: 'a31', name: 'Extra Granola', price: 1.50 },
      { id: 'a32', name: 'Almond Butter', price: 2.00 },
    ],
    dietary: ['vegan', 'gluten-free'],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord1',
    restaurantId: '1',
    restaurantName: "Mama Rosa's Trattoria",
    restaurantImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop',
    items: [
      {
        id: 'ci1',
        menuItem: mockMenuItems[0],
        quantity: 2,
        selectedAddOns: [{ id: 'a1', name: 'Extra Parmesan', price: 2.00 }],
        specialInstructions: 'Extra pepper please',
      },
    ],
    status: 'delivered',
    subtotal: 37.98,
    serviceFee: 5.70,
    deliveryFee: 3.99,
    smallOrderFee: 0,
    tax: 3.80,
    tip: 5.00,
    total: 56.47,
    createdAt: '2026-02-18T18:30:00Z',
    estimatedDelivery: '2026-02-18T19:15:00Z',
    deliveryAddress: {
      id: 'addr1',
      label: 'Home',
      street: '123 Palm Ave',
      city: 'Paradise City',
      state: 'CA',
      zip: '90210',
    },
    driver: {
      id: 'drv1',
      name: 'Michael Chen',
      rating: 4.9,
      vehicle: 'Toyota Prius • ABC123',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop',
      phone: '(555) 123-4567',
    },
  },
  {
    id: 'ord2',
    restaurantId: '2',
    restaurantName: 'Sakura Sushi Bar',
    restaurantImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop',
    items: [
      {
        id: 'ci2',
        menuItem: mockMenuItems[4],
        quantity: 1,
        selectedAddOns: [],
        specialInstructions: '',
      },
      {
        id: 'ci3',
        menuItem: mockMenuItems[5],
        quantity: 1,
        selectedAddOns: [{ id: 'a11', name: 'Extra Wasabi', price: 0.50 }],
        specialInstructions: '',
      },
    ],
    status: 'delivered',
    subtotal: 32.48,
    serviceFee: 4.87,
    deliveryFee: 4.49,
    smallOrderFee: 0,
    tax: 3.25,
    tip: 6.00,
    total: 51.09,
    createdAt: '2026-02-15T19:00:00Z',
    estimatedDelivery: '2026-02-15T19:45:00Z',
    deliveryAddress: {
      id: 'addr1',
      label: 'Home',
      street: '123 Palm Ave',
      city: 'Paradise City',
      state: 'CA',
      zip: '90210',
    },
  },
];

export const mockAddresses: Address[] = [
  {
    id: 'addr1',
    label: 'Home',
    street: '123 Palm Ave, Apt 4B',
    city: 'Paradise City',
    state: 'CA',
    zip: '90210',
    instructions: 'Ring doorbell twice',
  },
  {
    id: 'addr2',
    label: 'Work',
    street: '456 Ocean Blvd, Suite 200',
    city: 'Paradise City',
    state: 'CA',
    zip: '90210',
    instructions: 'Front desk will accept',
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: 'pm1',
    type: 'card',
    brand: 'Visa',
    last4: '4242',
    expiryMonth: 12,
    expiryYear: 2028,
    isDefault: true,
  },
  {
    id: 'pm2',
    type: 'card',
    brand: 'Mastercard',
    last4: '8888',
    expiryMonth: 6,
    expiryYear: 2027,
    isDefault: false,
  },
];

export const mockUser: User = {
  id: 'user1',
  name: 'Sarah Johnson',
  email: 'sarah@example.com',
  phone: '(555) 987-6543',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop',
  accountHealth: 98,
  addresses: mockAddresses,
  paymentMethods: mockPaymentMethods,
};
